version: '3.8'
services:
  mmchat_nestjs:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
    container_name: mmchat_nestjs
    restart: always
    entrypoint: ./.docker/entrypoint.sh
    environment:
      POSTGRES_HOST: mmchat_db
    networks:
      - mmchat-network
    volumes:
      - .:/home/node/app
    depends_on:
      - mmchat_db
    ports:
      - ${PORT}:${PORT}

  mmchat_db:
    image: postgres:13.3-alpine
    container_name: mmchat_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - mmchat-data:/var/lib/postgresql/data
    networks:
      - mmchat-network
      
volumes:
  mmchat-data:

networks:
  mmchat-network: