Project MMChat {
  database_type: 'PostgreSQL'
}

Table users {
  uuid uuid
  first_name varchar
  last_name varchar
  username varchar
  email varchar
  status Status
  password varchar
  avatar_url varchar

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table groups {
  uuid uuid
  name varchar
  image_url varchar
  description varchar
  creator_uuid int [ref: > users.uuid]

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table group_members {
  uuid uuid
  group_uuid uuid [ref: > groups.uuid]
  user_uuid int [ref: > users.uuid]

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table messages {
  uuid uuid
  content text
  group_id int [ref: > groups.uuid]
  sender_uuid uuid [ref: > users.uuid]
  receiver_uuid uuid [ref: > users.uuid]
  type MessageTypeEnum
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table messages_metadata {
  uuid uuid
  message_uuid int [ref: > messages.uuid]
  key varchar
  value varchar

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table storage_files {
  uuid uuid
  filename varchar
  path varchar
  url varchar
  size_bytes bigint

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table storage_files_metadata {
  uuid uuid
  file_uuid int [ref: > storage_files.uuid]
  key varchar
  value varchar

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table tasks_assignees {
  uuid uuid
  taks_id int [ref: > tasks.id]
  user_id int [ref: > users.uuid]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table tasks {
  id int [pk]
  title varchar
  description varchar
  label varchar
  state varchar
  priority PriorityEnum
  sprint varchar
  group_id int [ref: > groups.uuid]
  sender_uuid uuid [ref: > users.uuid]
  receiver_uuid uuid [ref: > users.uuid]

  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table contents {
  uuid int
  content text
  group_uuid int [ref: > groups.uuid]
  sender_uuid int [ref: > users.uuid]
  receiver_uuid uuid [ref: > users.uuid]
  type ContentTypeEnum
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum PriorityEnum {
  Urgent
  High
  Medium
  Low
  Lowest
}

Enum Status {
  Active
  Inactive
  Banned
  Quarantine
}

Enum ContentTypeEnum {
  note
  topic
}


Enum MessageTypeEnum {
  text
  image
  video
  audio
  file
  topic
  note
  task
}

//Relationship
// > many-to-one; < one-to-many; - one-to-one
